describe('d2h', function(){
    it('dec to hex', function(){
	expect('0').to.eql(d2h('0'))
	expect('1').to.eql(d2h('1'))
	expect('2').to.eql(d2h('2'))
	expect('3').to.eql(d2h('3'))
	expect('4').to.eql(d2h('4'))
	expect('5').to.eql(d2h('5'))
	expect('6').to.eql(d2h('6'))
	expect('7').to.eql(d2h('7'))
	expect('8').to.eql(d2h('8'))
	expect('9').to.eql(d2h('9'))
	expect('a').to.eql(d2h('10'))
	expect('b').to.eql(d2h('11'))
	expect('c').to.eql(d2h('12'))
	expect('d').to.eql(d2h('13'))
	expect('e').to.eql(d2h('14'))
	expect('f').to.eql(d2h('15'))
    })
})

describe('hex2bit', function(){
    it('hex to bit', function(){
	expect('00000000').to.eql(hex2bit('00'))
	expect('11111111').to.eql(hex2bit('ff'))
	expect('1111\n1010').to.eql(hex2bit('f\na'))
    })
})

describe('bitformat', function(){
    it('bit format', function(){
	expect('0000 0000 \n').to.eql(bitformat('00000000'))
    })
})

describe('isHex', function(){
    it('is hex', function(){
	expect(true).to.eql(isHex('0123456789abcdef'))
	expect(false).to.eql(isHex('123456789abcdefg'))
    })
})

describe('chengeEndian', function(){
    it('chenge Endian', function(){
	expect('abcd\n').to.eql(chengeEndian('cdab'))
	expect('cdab\n3412\n').to.eql(chengeEndian('abcd\n1234'))
    })
})

describe('b2h', function(){
    it('b2h', function(){
	expect('0').to.eql(b2h('0000'))
	expect('1').to.eql(b2h('0001'))
	expect('2').to.eql(b2h('0010'))
	expect('3').to.eql(b2h('0011'))
	expect('4').to.eql(b2h('0100'))
	expect('5').to.eql(b2h('0101'))
	expect('6').to.eql(b2h('0110'))
	expect('7').to.eql(b2h('0111'))
	expect('8').to.eql(b2h('1000'))
	expect('9').to.eql(b2h('1001'))
	expect('a').to.eql(b2h('1010'))
	expect('b').to.eql(b2h('1011'))
	expect('c').to.eql(b2h('1100'))
	expect('d').to.eql(b2h('1101'))
	expect('e').to.eql(b2h('1110'))
	expect('f').to.eql(b2h('1111'))
    })
})


describe('hex2ascii', function(){
    it('hex2ascii', function(){
	expect('!').to.eql(hex2ascii('21'))
	expect('"').to.eql(hex2ascii('22'))
	expect('#').to.eql(hex2ascii('23'))
	expect('$').to.eql(hex2ascii('24'))
	expect('%').to.eql(hex2ascii('25'))
	expect('&').to.eql(hex2ascii('26'))
	expect('\'').to.eql(hex2ascii('27'))
	expect('(').to.eql(hex2ascii('28'))
	expect(')').to.eql(hex2ascii('29'))
	expect('*').to.eql(hex2ascii('2A'))
	expect('+').to.eql(hex2ascii('2B'))
	expect(',').to.eql(hex2ascii('2C'))
	expect('-').to.eql(hex2ascii('2D'))
	expect('.').to.eql(hex2ascii('2E'))
	expect('/').to.eql(hex2ascii('2F'))
	expect('0').to.eql(hex2ascii('30'))
	expect('1').to.eql(hex2ascii('31'))
	expect('2').to.eql(hex2ascii('32'))
	expect('3').to.eql(hex2ascii('33'))
	expect('4').to.eql(hex2ascii('34'))
	expect('5').to.eql(hex2ascii('35'))
	expect('6').to.eql(hex2ascii('36'))
	expect('7').to.eql(hex2ascii('37'))
	expect('8').to.eql(hex2ascii('38'))
	expect('9').to.eql(hex2ascii('39'))
	expect(':').to.eql(hex2ascii('3A'))
	expect(';').to.eql(hex2ascii('3B'))
	expect('<').to.eql(hex2ascii('3C'))
	expect('=').to.eql(hex2ascii('3D'))
	expect('>').to.eql(hex2ascii('3E'))
	expect('?').to.eql(hex2ascii('3F'))
	expect('@').to.eql(hex2ascii('40'))
	expect('A').to.eql(hex2ascii('41'))
	expect('B').to.eql(hex2ascii('42'))
	expect('C').to.eql(hex2ascii('43'))
	expect('D').to.eql(hex2ascii('44'))
	expect('E').to.eql(hex2ascii('45'))
	expect('F').to.eql(hex2ascii('46'))
	expect('G').to.eql(hex2ascii('47'))
	expect('H').to.eql(hex2ascii('48'))
	expect('I').to.eql(hex2ascii('49'))
	expect('J').to.eql(hex2ascii('4A'))
	expect('K').to.eql(hex2ascii('4B'))
	expect('L').to.eql(hex2ascii('4C'))
	expect('M').to.eql(hex2ascii('4D'))
	expect('N').to.eql(hex2ascii('4E'))
	expect('O').to.eql(hex2ascii('4F'))
	expect('P').to.eql(hex2ascii('50'))
	expect('Q').to.eql(hex2ascii('51'))
	expect('R').to.eql(hex2ascii('52'))
	expect('S').to.eql(hex2ascii('53'))
	expect('T').to.eql(hex2ascii('54'))
	expect('U').to.eql(hex2ascii('55'))
	expect('V').to.eql(hex2ascii('56'))
	expect('W').to.eql(hex2ascii('57'))
	expect('X').to.eql(hex2ascii('58'))
	expect('Y').to.eql(hex2ascii('59'))
	expect('Z').to.eql(hex2ascii('5A'))
	expect('[').to.eql(hex2ascii('5B'))
	expect('\\').to.eql(hex2ascii('5C'))
	expect(']').to.eql(hex2ascii('5D'))
	expect('^').to.eql(hex2ascii('5E'))
	expect('_').to.eql(hex2ascii('5F'))
	expect('`').to.eql(hex2ascii('60'))
	expect('a').to.eql(hex2ascii('61'))
	expect('b').to.eql(hex2ascii('62'))
	expect('c').to.eql(hex2ascii('63'))
	expect('d').to.eql(hex2ascii('64'))
	expect('e').to.eql(hex2ascii('65'))
	expect('f').to.eql(hex2ascii('66'))
	expect('g').to.eql(hex2ascii('67'))
	expect('h').to.eql(hex2ascii('68'))
	expect('i').to.eql(hex2ascii('69'))
	expect('j').to.eql(hex2ascii('6A'))
	expect('k').to.eql(hex2ascii('6B'))
	expect('l').to.eql(hex2ascii('6C'))
	expect('m').to.eql(hex2ascii('6D'))
	expect('n').to.eql(hex2ascii('6E'))
	expect('o').to.eql(hex2ascii('6F'))
	expect('p').to.eql(hex2ascii('70'))
	expect('q').to.eql(hex2ascii('71'))
	expect('r').to.eql(hex2ascii('72'))
	expect('s').to.eql(hex2ascii('73'))
	expect('t').to.eql(hex2ascii('74'))
	expect('u').to.eql(hex2ascii('75'))
	expect('v').to.eql(hex2ascii('76'))
	expect('w').to.eql(hex2ascii('77'))
	expect('x').to.eql(hex2ascii('78'))
	expect('y').to.eql(hex2ascii('79'))
	expect('z').to.eql(hex2ascii('7A'))
	expect('{').to.eql(hex2ascii('7B'))
	expect('|').to.eql(hex2ascii('7C'))
	expect('}').to.eql(hex2ascii('7D'))
	expect('~').to.eql(hex2ascii('7E'))
	expect(' ').to.eql(hex2ascii('7F'))
				     
    })
})

